"""empty message

Revision ID: 765b0ec32ead
Revises: 42e3c0f35ca8
Create Date: 2022-11-07 11:34:39.097721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '765b0ec32ead'
down_revision = '42e3c0f35ca8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bike', sa.Column('cyclist_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bike', 'cyclist', ['cyclist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bike', type_='foreignkey')
    op.drop_column('bike', 'cyclist_id')
    # ### end Alembic commands ###
