"""Added bike model

Revision ID: 7bd7ebb7eaee
Revises: c30c16f92463
Create Date: 2022-11-06 21:46:02.344702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bd7ebb7eaee'
down_revision = 'c30c16f92463'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bike', sa.Column('price', sa.Integer(), nullable=True))
    op.add_column('bike', sa.Column('size', sa.Integer(), nullable=True))
    op.add_column('bike', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bike', 'type')
    op.drop_column('bike', 'size')
    op.drop_column('bike', 'price')
    # ### end Alembic commands ###
